#!/usr/bin/env bash

NAME=varnishncsa
FORMAT=""
DAEMON=/usr/bin/${NAME}
DAEMON_OPTS=""
PID_FILE="/var/run/${NAME}.pid"
DESC="Varnish 2 Gelf"

if [ -f /etc/default/${NAME} ]; then
  # Include configuration
  . /etc/default/${NAME}
fi


install -o nobody -d $(dirname ${PID_FILE})

echo "Starting ${DESC}"

${DAEMON} -P ${PID_FILE} ${DAEMON_OPTS};
sleep 20; # Wait for the daemon to start and write PID to the PID file

PID=$(cat ${PID_FILE})
echo "${DESC} started with PID: $PID";

trap "echo Reloading ${DESC}; /etc/service/${NAME}/reload;" SIGHUP
trap "echo Stopping ${DESC}; /etc/service/${NAME}/restart && exit 0" SIGTERM SIGINT

while true; do # Iterate to keep job running.
    ps -p ${PID} > /dev/null
    if [ $? == "1" ]; then
        echo "Process got killed, exiting script..."
        break;
    fi
    sleep 1 # Wake up to handle signals
done

